### ISSUE TITLE
Refactor github workflow to only build image on main branch commits

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/release-manager#130]
## Suggestion

Refactor the github workflow to only build an image on main branch commits and not not for PR.

Example of code
```
name: "CI - JDK 11 Build"

on:
    push:
        branches: [ main ]
        tags: ['*.*']
    pull_request:
        branches: [ main ]

jobs:
    build-jdk11:
        name: "JDK 11 Build"
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   name: Setup AdoptOpenJDK
                uses: joschi/setup-jdk@v2.3.0
                with:
                    java-version: 11

            -   name: Build
                run: ./mvnw clean package -X
                
    build-container:
        name: "Build container image"
        runs-on: ubuntu-latest
        if: github.event_name != 'push'
        steps:
            -   uses: actions/checkout@v2
            -   name: Container meta
                id: container_meta
                uses: crazy-max/ghaction-docker-meta@v2
                with:
                    # list of Docker images to use as base name for tags
                    images: |
                        quay.io/snowdrop/release-manager
                    # generate Docker tags based on the following events/attributes
                    tags: |
                        type=semver,pattern={{version}}
                        type=semver,pattern={{major}}.{{minor}}
                        type=semver,pattern={{major}}
                        type=sha
                        type=ref,event=tag

            -   name: Login to DockerHub
                uses: docker/login-action@v1
                with:
                  registry: quay.io
                  username: ${{ secrets.QUAY_USERNAME }}
                  password: ${{ secrets.QUAY_ROBOT_TOKEN }}

            -   name: Build and push
                id: container_build
                uses: docker/build-push-action@v2
                with:
                    context: .
                    file: ./ci/Dockerfile.jvm
                    push: ${{ github.event_name != 'pull_request' }}
                    # tags: quay.io/snowdrop/release-manager:latest
                    tags: ${{ steps.container_meta.outputs.tags }}
                    labels: ${{ steps.container_meta.outputs.labels }}

            -   name: Image digest
                run: echo ${{ steps.container_build.outputs.digest }}
```

WDYT: @jacobdotcosta @aureamunoz
